### ISSUE TITLE
Issue with half-supported native implementation

### ISSUE THREAD

**Issue by Miced** [WebReflection/url-search-params#30] opened 2018-03-05 10:35 UTC
Some browser older versions include basic support for URLSearchParams but lack advanced features such as constructor USVString or init object support.

e.g. in Firefox v52 record as init object is not supported, but there is a native URLSearchParams constructor. This results in the polyfill not being used, but also the native implementation not working as intended.

**Comment by WebReflection** [comment] 2018-03-05 10:45
I see, this looks like a duplicate of this one then: https://github.com/WebReflection/url-search-params/issues/28

would you be happy with this polyfill taking over/replacing global constructor in those cases?

**Comment by Miced** [comment] 2018-03-05 10:48
Indeed it seems duplicate of #28 but I was not certain if that was the only problem with that issue.

I believe this would be the only solution in those cases, if they can be distinguished (not replacing native implementation on all cases).

**Closed** 2018-06-23 09:50 UTC
