### ISSUE TITLE
some mobile browser have  URLSearchParams but not surpport  `new URLSearchParams({a: 1})).toString() === 'a=1'`

### ISSUE THREAD

**Issue by xiaoshude** [WebReflection/url-search-params#28] opened 2017-11-30 03:13 UTC
please add checking like : ` isSupportObjectConstructor = nativeURLSearchParams && (new nativeURLSearchParams({a: 1})).toString() === 'a=1'`

**Comment by ljharb** [comment] 2017-11-30 07:13
(except always `String(x)` and never `x.toString()`)

**Comment by WebReflection** [comment] 2017-11-30 10:38
Apologies I don't understand what is this about.

> some mobile browser

which one? I like counter-verify my changes.

> have URLSearchParams but not surpport `new URLSearchParams({a: 1})).toString() === 'a=1'`

there are so many things to compare there ..
  * no support for `new URLSearchParams`?
  * no support for an object passed to the constructor?
  * no support for `toString()`?
  * the `toString()` produces something else?
  * where is the related browser bug, if any?

Thanks

**Comment by tricoder42** [comment] 2018-06-23 09:39
Hey, I encountered the same issue as well. The problem is with passing an object as a first parameter to constructor: `new nativeURLSearchParams({a: 1})`. Then, `.toString()` will output `[Object ...]`.

It works in regular browser, but it didn't work in electron-chrome (for testing). I'm adding parameters using `.append` instead and everything work fine in all envs.

```js
// Bad
const search = new URLSearchParams({ a: 1 })
search.toString() === '[Object ...]'

// Good
const search = new URLSearchParams()
search.append('a', 1)
search.toString() === 'a=1'
```

**Comment by WebReflection** [comment] 2018-06-25 08:42
I am going to close this since I believe it's been covered already.

If not, please specify a browser I can test and counter verify to propose a similar work around.

**Closed** 2018-06-25 09:18 UTC

**Comment by tricoder42** [comment] 2018-06-25 12:33
@WebReflection You're right, the problem is caused by broken URLSearchParams in electron browser. However, I have to use this condition: `new URLSearchParams({ q: 1 }).toString() !== 'q=1'` to check if polyfill is working correctly.

Anyway, thanks for this library!

**Comment by biuuu** [comment] 2018-11-18 13:42
@WebReflection 
Similar problem on Android Chrome/56.0.2924.87 .
`new URLSearchParams('q=%2B').get('q') !== '+'` return `false` ,
but `new URLSearchParams({q:'+'}).get('q')` return `null` .

**Comment by WebReflection** [comment] 2018-11-18 13:51
Again ... This has been covered.
https://github.com/WebReflection/url-search-params/blob/master/README.md#ios-10--other-platforms-bug
